### ISSUE TITLE
code crashes

### ISSUE THREAD

**Issue by bardware** [KamasamaK/vscode-cfml#17]
Hi,

today, I start code and during the start the CPU and RAM of my PC are fully used and `code` eventually crashes. I look at the output of code when started with `--verbose` flag and only see `workbench.main.js` as the error source. I started to uninstall plugins that appeared in the output. This plugin had exceptions:

```
[65304:0711/164501.610:INFO:CONSOLE(270)] "%c[Extension Host]%", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (270)
[65304:0711/164501.610:INFO:CONSOLE(270)] "%c[Extension Host] %cTypeError: Cannot read property 'split' of undefined
        at getComponentNameFromDotPath (C:\vscode\cfml\exts\KamasamaK.vscode-cfml-0.4.0\out\entities\component.js:305:16)
        at Object.parseComponent (C:\vscode\cfml\exts\KamasamaK.vscode-cfml-0.4.0\out\entities\component.js:166:33)
        at vscode_1.workspace.openTextDocument.then (C:\vscode\cfml\exts\KamasamaK.vscode-cfml-0.4.0\out\features\cachedEntities.js:268:53)
        at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:729)
        at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:81:61)
        at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:866)
        at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:307)
        at e.resolveOk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:554:1000)
        at e._receiveReply (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:657:394)
        at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:656:693)
        at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:655:544
        at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:658:673
        at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:599
        at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:97:917)
        at u (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:721)
        at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:159:898)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:191:7)
        at readableAddChunk (_stream_readable.js:178:18)
        at Socket.Readable.push (_stream_readable.js:136:10)
        at Pipe.onread (net.js:560:20) %c(at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:93:996)", source: file:///C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js (270)
```
After uninstall, code seems to work again. No idea if it was caused by your plugin.
I raised an issue at [Microsoft's](https://github.com/Microsoft/vscode/issues/54062) as well.

**Comment by KamasamaK** [comment]
There is an error from the extension there, but I don't see how it would cause the CPU/RAM issue and crash the application. When an error like that occurs, it will usually just break the function that is running. I will look into what the cause could be.

The indexing of all components at startup is CPU intensive and possibly memory as well. You can disable that in the settings if it is causing an issue.

**Comment by bardware** [comment]
Thanks for the reply.  
I managed to take a screenshot of Taskmanager briefly before the crash.
There was a massive number of these processes. I cannot say if these are created by a plugin or VSCode itself.

![20180711_vscode](https://user-images.githubusercontent.com/802702/42595289-19e8a8ca-8552-11e8-8be2-ba7023b37e37.PNG)

**Comment by KamasamaK** [comment]
Were you able to find a solution for this? I believe the latest version of the extension does address the specific error you posted here, but again I do not believe that was the cause of the behavior you were experiencing.

**Comment by KamasamaK** [comment]
Closing due to lack of feedback
