### ISSUE TITLE
Errors trying to use the extension

### ISSUE THREAD

**Issue by adelisle-cegid** [KamasamaK/vscode-cfml#21]
With latest vscode (1.27.2) and latest extension (0.4.1), I am getting this error reported in Log (Window):

```
[2018-09-25 11:16:06.230] [renderer1] [info] no standard startup: not the explorer viewlet
[2018-09-25 11:16:14.057] [renderer1] [info] no standard startup: panel is active
[2018-09-25 11:27:12.724] [renderer1] [info] no standard startup: not a new window
[2018-09-25 11:27:17.212] [renderer1] [error] Cannot read property 'name' of undefined: TypeError: Cannot read property 'name' of undefined
	at Function.getComponentSymbols (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\features\documentSymbolProvider.js:46:69)
	at CFMLDocumentSymbolProvider.<anonymous> (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\features\documentSymbolProvider.js:31:85)
	at Generator.next (<anonymous>)
	at C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\features\documentSymbolProvider.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\features\documentSymbolProvider.js:3:12)
	at CFMLDocumentSymbolProvider.provideDocumentSymbols (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\features\documentSymbolProvider.js:24:16)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:746:373
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:108:466
	at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:86:460)
	at Object.t.asWinJsPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:108:431)
	at e.provideDocumentSymbols (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:746:327)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:761:596
	at e._withAdapter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:761:91)
	at e.$provideDocumentSymbols (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:761:558)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:309)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:27)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:679:802)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:678:993)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:791
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:597
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:787)
	at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
[2018-09-25 11:27:19.312] [renderer1] [error] Cannot read property 'name' of undefined: TypeError: Cannot read property 'name' of undefined
	at Function.getComponentSymbols (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\features\documentSymbolProvider.js:46:69)
	at CFMLDocumentSymbolProvider.<anonymous> (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\features\documentSymbolProvider.js:31:85)
	at Generator.next (<anonymous>)
	at C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\features\documentSymbolProvider.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\features\documentSymbolProvider.js:3:12)
	at CFMLDocumentSymbolProvider.provideDocumentSymbols (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\features\documentSymbolProvider.js:24:16)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:746:373
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:108:466
	at new n.Class.derive._oncancel (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:86:460)
	at Object.t.asWinJsPromise (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:108:431)
	at e.provideDocumentSymbols (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:746:327)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:761:596
	at e._withAdapter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:761:91)
	at e.$provideDocumentSymbols (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:761:558)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:309)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:681:27)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:679:802)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:678:993)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:791
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:597
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:787)
	at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
[2018-09-25 11:28:58.799] [renderer1] [error] Illegal argument: character must be non-negative: Error: Illegal argument: character must be non-negative
	at Object.t.illegalArgument (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:91:544)
	at new e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:475:904)
	at e.translate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:477:541)
	at Object.parseScriptFunctions (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\entities\userFunction.js:146:102)
	at Object.parseComponent (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\entities\component.js:197:40)
	at vscode_1.workspace.openTextDocument.then (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\features\cachedEntities.js:331:53)
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:79:572)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:924)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:790)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:231)
	at e.resolveOk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:578:1000)
	at e._receiveReply (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:680:669)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:679:218)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:791
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:597
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:787)
	at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
[2018-09-25 11:28:58.799] [renderer1] [error] Cannot read property 'toLowerCase' of undefined: TypeError: Cannot read property 'toLowerCase' of undefined
	at Object.equalsIgnoreCase (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\utils\textUtil.js:24:20)
	at isDataType (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\entities\dataType.js:177:28)
	at Object.getDataTypeAndUri (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\entities\dataType.js:200:13)
	at parsedPropertyAttributes.forEach (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\entities\property.js:90:63)
	at Map.forEach (<anonymous>)
	at Object.parseProperties (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\entities\property.js:84:38)
	at Object.parseComponent (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\entities\component.js:143:32)
	at vscode_1.workspace.openTextDocument.then (C:\Users\user\.vscode\extensions\kamasamak.vscode-cfml-0.4.1\out\features\cachedEntities.js:331:53)
	at Object.g [as _notify] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:79:572)
	at Object.enter (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:82:924)
	at n.Class.derive._oncancel._run (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:790)
	at n.Class.derive._oncancel._completed (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:84:231)
	at e.resolveOk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:578:1000)
	at e._receiveReply (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:680:669)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:679:218)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:791
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:98:597
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:99:917)
	at a (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:787)
	at Socket._socketDataListener (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:164:1006)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**Comment by KamasamaK** [comment]
Please check if this is still occurring in v0.5.0.

**Comment by adelisle-cegid** [comment]
Confirming it was indeed fixed, sorry for the delay.
