### ISSUE TITLE
No symbols found in CFC after update to 0.5.0

### ISSUE THREAD

**Issue by trmatt** [KamasamaK/vscode-cfml#28]
After the recent update to 0.5.0, I noticed that symbols for my CFCs are no longer found.

I also notice a notification indicating components are being cached after launching the symbol browser (CTRL+SHIFT+O), which disappears almost immediately.

Reverting to 0.4.1 restores functionality.

VSC detail is:

Version: 1.30.2 (user setup)
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:54:13.295Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 6.1.7601

Installed extensions are:

[enabled]
KamasamaK.vscode-cfml
ms-mssql.mssql
Tyriar.sort-lines

[disabled]
mitchdenny.ecdc
ms-vscode.csharp
tomoki1207.pdf

**Comment by KamasamaK** [comment]
If you have interfaces in your workspace, this might be related to #27 which I am working on a fix for. If not, I would need more information. If you open Developer Tools (`Ctrl`+`Shift`+`I`) it will list the errors encountered. Please paste any originating from this extension.

**Comment by Miguel-F** [comment]
I think I may be having this same issue but I have no interfaces in my workspace (that I am aware of).  I'm not sure what @trmatt means by "symbols".  For me, the CFML extension no longer shows the popup with documentation for CF functions/tags (the signature help and hover documentation).

![capture](https://user-images.githubusercontent.com/6524995/51276289-4c7a7180-19a2-11e9-9cff-c5b48bf9051a.png)

Nothing appears when I hover over.  The only difference I know of is that I installed the CFLint extension.  I don't know if that extension is over-riding the CFML extension popup on hover.  Do you know of any conflicts between these two extensions?

**Comment by KamasamaK** [comment]
There is no conflict with the two extensions that would cause something like that. I wrote and use both. Please follow the same instructions for providing more information.

**Comment by Miguel-F** [comment]
The documentation tool tips do appear to be working.  Sorry for the confusion.  Our IT department recently installed a local web proxy (installed on our machines) and it was blocking access to the documentation websites.  This does seem to be working once connectivity was restored.
Thanks for these extensions @KamasamaK .

**Comment by KamasamaK** [comment]
@Miguel-F The documentation is retrieved from the GitHub repo of CFDocs, but there are settings to use a local copy if you would like to avoid this issue.

**Comment by KamasamaK** [comment]
Please see if v0.5.1 fixes your issues.

**Comment by chapmandu** [comment]
I still receive the same "toLowerCase" errors when attempting to "refresh cache for workspace definitions".

When using the "Go to Definition" feature, I receive the error below:

ERR Cannot convert undefined or null to object: TypeError: Cannot convert undefined or null to object
	at Function.values (<anonymous>)
	at Object.searchAllFunctionNames (/Users/adam/.vscode/extensions/kamasamak.vscode-cfml-0.5.1/out/features/cachedEntities.js:217:28)
	at CFMLDefinitionProvider.provideDefinition (/Users/adam/.vscode/extensions/kamasamak.vscode-cfml-0.5.1/out/features/definitionProvider.js:253:64)
	at <anonymous>

**Comment by jclausen** [comment]
I can confirm that this issue still exists on 0.5.1.  Rolling back to 0.4.x fixes the issue.

**Comment by KamasamaK** [comment]
@chapmandu Are you sure they're the same `toLowerCase` errors? That function now explicitly checks for `undefined`.

**Comment by KamasamaK** [comment]
I've added a few more fixes in v0.5.2 but it's difficult to say if they'll solve all the problems here without a sample file or stack trace.

**Comment by trmatt** [comment]
Unfortunately, no change in behaviour for me with v0.5.2.

I'm happy with 0.4.1, so no harm no foul on my part (great extension!).

I just noticed that things didn't work out when I upgraded.

If you have anything you'd like me to try to generate a stack trace, I'm game. As it stands though, when I enable the Developer Tools, I get nothing (sometimes stray errors from previous activity, but when I update the extension, and launch the tools and try to open files/search for symbols, it triggers no activity).

**Comment by KamasamaK** [comment]
@chapmandu  The hover provider rejection is unrelated to this issue. At this point, I don't think I will be able to reproduce the issue without a sample.

**Comment by chapmandu** [comment]
@KamasamaK Please let me know how I can help get what you need

**Comment by trmatt** [comment]
I've tried the extension again with the new VS Code release, and no changes.

Version: 1.31.0 (user setup)
Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
Date: 2019-02-05T22:35:56.624Z
Electron: 3.1.2
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601

**Comment by trmatt** [comment]
Version 0.5.3 of vscode-cfml (in VS Code 1.31) seems to have restored symbol lookup.

A few minor things seem to still be present (re: component caching taking a bit; and CTRL+SHIFT+O and ":" (colon) to sort symbols didn't pan out until after a restart), but nothing terrible, or particularly reproducible.

Many thanks for sorting things out!

**Comment by jclausen** [comment]
Looks good!  I think you can mark this one as closed.  Thanks! :)

**Comment by KamasamaK** [comment]
Good to hear this was resolved.
