### ISSUE TITLE
Extension stops working with "provider FAILED" exception in vscode log

### ISSUE THREAD

**Issue by redtopia** [KamasamaK/vscode-cfml#47]
I continually getting the following error, which might be the cause of CFDocs and snippets no longer working until I restart vscode. This could be related to this issue I previously reported: https://github.com/KamasamaK/vscode-cfml/issues/39. This happens every day, multiple times per day and I'm forced to restart vscode to get CFDocs/snippets to work in CFML files.

The error is:

```
[2020-04-13 10:48:26.963] [exthost] [error] [KamasamaK.vscode-cfml] provider FAILED
[2020-04-13 10:48:26.963] [exthost] [error] Error: Illegal argument: character must be non-negative
	at Object.t.illegalArgument (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10:784)
	at new e (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:400:473)
	at new e (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:398:174)
	at BackwardIterator.getPosition (c:\Users\John Smith\.vscode\extensions\kamasamak.vscode-cfml-0.5.3\out\utils\contextUtil.js:82:16)
	at Object.getStartSigPosition (c:\Users\John Smith\.vscode\extensions\kamasamak.vscode-cfml-0.5.3\out\utils\contextUtil.js:831:39)
	at CFMLSignatureHelpProvider.provideSignatureHelp (c:\Users\John Smith\.vscode\extensions\kamasamak.vscode-cfml-0.5.3\out\features\signatureHelpProvider.js:37:51)
	at c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:671
	at c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:54:761
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:54:733)
	at U.provideSignatureHelp (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:642)
	at c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:658:825
	at e._withAdapter (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:649:159)
	at e.$provideSignatureHelp (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:658:803)
	at e._doInvokeHandler (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:752:683)
	at e._invokeHandler (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:752:375)
	at e._receiveRequest (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:750:953)
	at e._receiveOneMessage (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:749:832)
	at c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:748:34
	at e.fire (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:497)
	at v.fire (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:206:615)
	at c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:919:744
	at e.fire (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:497)
	at v.fire (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:206:615)
	at t.PersistentProtocol._receiveMessage (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:211:17)
	at c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:208:155
	at e.fire (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:497)
	at p.acceptChunk (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:204:129)
	at c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:203:483
	at Socket.t (c:\Users\John Smith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:212:565)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by redtopia** [comment]
When I keep the log open, I can see these error logged in real time as I'm editing. I did one editing sequence that took about 2 minutes and watched 22 of these errors come in.

**Comment by redtopia** [comment]
I should also note that when I get in the state where the extension "stops working", auto-close settings no longer work either in cfscript or tag mode (both cfml and html). However, syntax coloring still works.
