### ISSUE TITLE
Extension becomes unresponsive from time to time. 

### ISSUE THREAD

**Issue by cybersonic** [KamasamaK/vscode-cfml#72]
I have noticed the extension now becomes unresponsive. It is evidenced by being unable to add tabs or do block comments (using CMD+Shift+/ for example) , intellisense doesnt show up. 

Looking in the output window, and selecting `Log(Window)` I can see the following entry:

`UNRESPONSIVE extension host, 'KamasamaK.vscode-cfml' took 99% of 5065.345ms, saved PROFILE here: 'file:///var/folders/cs/g_j_5_v16f17plt9jb2hdz7r0000gn/T/exthost-ca70bc.cpuprofile' [{"id":"gc","total":38664,"percentage":1},{"id":"KamasamaK.vscode-cfml","total":5026188,"percentage":99}]
`

I have attached the profile
[exthost-ca70bc.cpuprofile.txt](https://github.com/KamasamaK/vscode-cfml/files/7697187/exthost-ca70bc.cpuprofile.txt)

**Comment by Scatterblak** [comment]
I fixed this on mine by moving the CFDocs repository to my local machine.  Just download the repository from github, and edit the JSON for the extension to use local instead of remote - then set the path to the 'data\language' directory in the local repository. Mine looks like this:

"cfml.cfDocs.localPath": "E:\\CFDocs_GitHub\\cfdocs-master\\data\\en\\"

So far so good...

**Comment by Scatterblak** [comment]
...and, after this last update, it's unresponsive again. :(

**Comment by Scatterblak** [comment]
...still tracking it down. Looks like it has a 'listener LEAK':

====================================================
[f21] potential listener LEAK detected, having 1124 listeners already. MOST frequent listener (1115):
Error
    at i.create (event.ts:601:25)
    at _event._event [as onDidChange] (event.ts:720:25)
    at l (codeAction.ts:151:28)
    at codeActionModel.ts:251:54
    at w (async.ts:25:19)
    at u._signalChange (codeActionModel.ts:251:21)
    at u._createEventAndSignalChange (codeActionModel.ts:135:8)
    at u.trigger (codeActionModel.ts:50:15)
    at codeActionModel.ts:68:9
    at async.ts:779:4
check @ event.ts:588

...when this happens, on my box, it's usually followed by this:

==================================================
WARN Error: Aborted onWillSaveTextDocument-event after 1750ms
    at mainThreadSaveParticipant.ts:37:18
log.ts:313   ERR Illegal argument: character must be non-negative: Error: Illegal argument: character must be non-negative
	at k (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:7:1279)
	at new g (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:78:87309)
	at new g (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:78:86640)
	at BackwardIterator.getPosition (c:\Users\Owner\.vscode\extensions\kamasamak.vscode-cfml-0.5.4\out\utils\contextUtil.js:102:16)
	at getStartSigPosition (c:\Users\Owner\.vscode\extensions\kamasamak.vscode-cfml-0.5.4\out\utils\contextUtil.js:851:39)
	at CFMLSignatureHelpProvider.provideSignatureHelp (c:\Users\Owner\.vscode\extensions\kamasamak.vscode-cfml-0.5.4\out\features\signatureHelpProvider.js:56:75)
	at pe.provideSignatureHelp (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:58378)
	at c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:78534
	at ee._withAdapter (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:67201)
	at ee.$provideSignatureHelp (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:78509)
	at i._doInvokeHandler (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13689)
	at i._invokeHandler (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13371)
	at i._receiveRequest (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:12090)
	at i._receiveOneMessage (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:10843)
	at c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:8950
	at b.invoke (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at p.deliver (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at v.fire (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at a.fire (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19042)
	at c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:17079
	at b.invoke (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at p.deliver (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at v.fire (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at a.fire (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19042)
	at r._receiveMessage (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:23854)
	at c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:21224
	at b.invoke (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at p.deliver (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at v.fire (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at v.acceptChunk (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:15873)
	at c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:15003
	at Socket.d (c:\Users\Owner\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:26763)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
